rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  ProcedureSyntax,
  RedundantSyntax
]

OrganizeImports.groupedImports = Merge
OrganizeImports.removeUnused = true
OrganizeImports.targetDialect = Scala3
