addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.10.4")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.14.3")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"     % "1.1.3")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"      % "1.6.1")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "2.0.12")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.12.0")
