package dev.aegiskms.crypto.software

import dev.aegiskms.core.SigAlgorithm
import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers

import java.nio.file.attribute.PosixFilePermission
import java.nio.file.{Files, Path}
import java.security.KeyStore

/** Storage-layer tests for [[SoftwareKeyStore]] — the file lifecycle and failure modes that
  * `SoftwareRootOfTrustSpec` exercises only indirectly.
  *
  * These matter because the keystore file *is* the durability story for the software backend: if it silently
  * fails to persist, or accepts a file it did not create, keys go missing in ways the crypto tests would not
  * catch.
  */
final class SoftwareKeyStoreSpec extends AnyFunSuite with Matchers:

  test("a fresh keystore starts at generation 1 and rotation counts up from there") {
    val ks = SoftwareKeyStore.ephemeral()

    ks.currentKekVersion shouldBe 1
    ks.rotateKek() shouldBe 2
    ks.rotateKek() shouldBe 3
    ks.currentKekVersion shouldBe 3
  }

  test("every generation stays retrievable after rotation, with distinct key material") {
    val ks = SoftwareKeyStore.ephemeral()
    ks.rotateKek()
    ks.rotateKek()

    val keys = (1 to 3).map(v => ks.kek(v).getEncoded.toSeq)

    keys.distinct.size shouldBe 3
    all(keys.map(_.size)) shouldBe 32
  }

  test("asking for a generation that does not exist names both the request and the current state") {
    val ks = SoftwareKeyStore.ephemeral()

    val ex = intercept[IllegalArgumentException](ks.kek(7))
    ex.getMessage should include("v7")
    ex.getMessage should include("current is v1")
  }

  test("signingKeyPair is stable across calls — the lazy generation happens exactly once") {
    val ks = SoftwareKeyStore.ephemeral()

    val (priv1, pub1) = ks.signingKeyPair(SigAlgorithm.EcdsaSha256)
    val (priv2, pub2) = ks.signingKeyPair(SigAlgorithm.EcdsaSha256)

    priv1.getEncoded shouldBe priv2.getEncoded
    pub1.getEncoded shouldBe pub2.getEncoded
  }

  test("the RSA and EC keypairs are distinct and carry their expected algorithms") {
    val ks = SoftwareKeyStore.ephemeral()

    val (ecPriv, _)  = ks.signingKeyPair(SigAlgorithm.EcdsaSha256)
    val (rsaPriv, _) = ks.signingKeyPair(SigAlgorithm.RsaPssSha256)

    ecPriv.getAlgorithm shouldBe "EC"
    rsaPriv.getAlgorithm shouldBe "RSA"
    ecPriv.getEncoded shouldNot be(rsaPriv.getEncoded)
  }

  test("atPath creates missing parent directories") {
    withTempDir { dir =>
      val nested = dir.resolve("a/b/c/keystore.p12")

      SoftwareKeyStore.atPath(nested, "pw")

      Files.exists(nested) shouldBe true
    }
  }

  test("the keystore file is created owner-readable only") {
    withTempDir { dir =>
      val path = dir.resolve("keystore.p12")
      SoftwareKeyStore.atPath(path, "pw")

      Files.getPosixFilePermissions(path).toArray.toSet shouldBe
        Set(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)
    }
  }

  test("a signing keypair generated by one instance is reused by the next, not regenerated") {
    withTempDir { dir =>
      val path = dir.resolve("keystore.p12")

      val (priv, _)  = SoftwareKeyStore.atPath(path, "pw").signingKeyPair(SigAlgorithm.EcdsaSha256)
      val (again, _) = SoftwareKeyStore.atPath(path, "pw").signingKeyPair(SigAlgorithm.EcdsaSha256)

      again.getEncoded shouldBe priv.getEncoded
    }
  }

  test("a PKCS#12 file Aegis did not create is rejected instead of being silently adopted") {
    withTempDir { dir =>
      val path = dir.resolve("foreign.p12")
      val ks   = KeyStore.getInstance("PKCS12")
      ks.load(null, "pw".toCharArray)
      val out = new java.io.ByteArrayOutputStream()
      ks.store(out, "pw".toCharArray)
      Files.write(path, out.toByteArray)

      val ex = intercept[IllegalStateException](SoftwareKeyStore.atPath(path, "pw"))
      ex.getMessage should include("not created by Aegis")
    }
  }

  test("a corrupt keystore file fails loudly rather than booting with no key material") {
    withTempDir { dir =>
      val path = dir.resolve("corrupt.p12")
      Files.write(path, "this is not a keystore".getBytes("UTF-8"))

      an[Exception] should be thrownBy SoftwareKeyStore.atPath(path, "pw")
    }
  }

  test("a completed save leaves no stray .tmp file beside the keystore") {
    withTempDir { dir =>
      val path = dir.resolve("keystore.p12")
      val ks   = SoftwareKeyStore.atPath(path, "pw")
      ks.rotateKek()

      Files.list(dir).toArray.map(_.toString).count(_.endsWith(".tmp")) shouldBe 0
    }
  }

  private def withTempDir(f: Path => Any): Unit =
    val dir = Files.createTempDirectory("aegis-software-keystore")
    try
      f(dir)
      ()
    finally
      Files.walk(dir).sorted(java.util.Comparator.reverseOrder()).forEach(Files.deleteIfExists(_))
